### ISSUE TITLE
Optimal path isn't working for the other pictures 

### ISSUE THREAD

**Issue by Bharathh30** [vipulchaturvedi/treesense-imaging#4]
Was trying to submit another image that is not mentioned in the presentation , it is just giving the percentage of the green cover and the land cover instead of giving the optimal pathing

**Comment by lag25** [comment]
Hi @Bharathh30, we had to remove Optimal Pathing from the website due to its computational needs. If you are interested in trying out the functionality, I would suggest using the StructuredOptimalPathing notebook (can be found [here](https://github.com/lag25/ForestPathPlanner/blob/main/StructuredOptimalPathing.ipynb)). Execute all the cells sequentially and also don't forget to have the PATH variable point to the address of your image along with the suitable start and target coordinates. The execution will take some time depending upon the dimensions of the image (Generally upto 10 mins even). Let me if you come across any other issue :)
